name: PR Unit Test

on:
  pull_request:
    types:
      - review_requested
      - review_request_removed
      - reopened
  pull_request_review:
    types:
      - submitted

jobs:
  test-and-build:
    name: Test and Build on Reviewer Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack (Yarn v4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: npm run test

      - name: Build stage
        run: npm run package
